In [1]:
import numpy as np

In [2]:
arr = np.array( [1,2,3] )
print(type(arr), arr)

<class 'numpy.ndarray'> [1 2 3]


In [3]:
print(arr.shape)

(3,)


In [4]:
print(arr[0], arr[1], arr[2])

1 2 3


In [6]:
arr[0] = 5
arr

array([5, 2, 3])

In [7]:
arr2 = np.array( [[1,2,3],
                   [4,5,6]])

In [9]:
type(arr2), arr2, arr2.shape

(numpy.ndarray, array([[1, 2, 3],
        [4, 5, 6]]), (2, 3))

In [10]:
print(arr2[0,0], arr2[0,1], arr2[1,0])

1 2 4


In [11]:
arr3 = np.arange(32)
arr3, arr3.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]), (32,))

In [12]:
arr3.reshape(4,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [13]:
arr3.reshape(2,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]])

In [14]:
arr3.reshape(-1,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [16]:
a = np.zeros( (2,2) )
a

array([[0., 0.],
       [0., 0.]])

In [18]:
b = np.ones( (3,3) )
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
c = np.full((5,5), -1)
c

array([[-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1]])

In [21]:
d = np.eye(2)
d

array([[1., 0.],
       [0., 1.]])

In [22]:
e = np.random.random((2,2))
e

array([[0.55655296, 0.89168551],
       [0.13397628, 0.53109392]])

In [23]:
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
arr, arr.shape

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]), (3, 4))

In [32]:
row_r1 = arr[1,:]
row_r1

array([5, 6, 7, 8])

In [33]:
row_r2 = arr[1:2, :]
row_r2

array([[5, 6, 7, 8]])

In [34]:
col_r1 = a[:, 1]
col_r1

array([0., 0.])

In [35]:
col_r2 = a[:, 1:2]
col_r2

array([[0.],
       [0.]])

In [36]:
arr = np.array( [[1,2], [3,4], [5,6]])
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [38]:
arr[[0,1,2], [0,1,0]]

array([1, 4, 5])

In [40]:
arr[0,0], arr[1,1], arr[2,0]

(1, 4, 5)

In [42]:
arr[[0,0], [1,1]]

array([2, 2])

In [43]:
arr[0,1], arr[0,1]

(2, 2)

In [51]:
arr = np.arange(1,13).reshape(4,3)
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [52]:
arr2 = np.array([0,2,0,1])

In [54]:
arr[np.arange(4),arr2]

array([ 1,  6,  7, 11])

In [56]:
arr[np.arange(4), arr2] *= 10

In [57]:
arr

array([[ 10,   2,   3],
       [  4,   5,  60],
       [ 70,   8,   9],
       [ 10, 110,  12]])

In [59]:
arr = np.arange(1,13).reshape(4,3)
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [61]:
bool_idx = ( arr >= 5)
bool_idx

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [62]:
arr[bool_idx]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [63]:
arr[arr >= 10]

array([10, 11, 12])

In [65]:
arr1 = np.array([1,2])
arr1, arr1.dtype

(array([1, 2]), dtype('int32'))

In [66]:
arr2 = np.array([1.0,2.0])
arr2, arr2.dtype

(array([1., 2.]), dtype('float64'))

In [67]:
arr3 = np.array([1,2], dtype=np.int64)
arr3, arr3.dtype

(array([1, 2], dtype=int64), dtype('int64'))

In [69]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [75]:
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [76]:
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [77]:
print(x * y)
print(np.multiply(x, y))


[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [79]:
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [80]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [81]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])


In [82]:
v = np.array([9,10])
w = np.array([11, 12])


In [84]:
print(v.dot(w))
print(np.dot(v, w))

219
219


In [85]:
print(x.dot(v))
print(np.dot(x, v))

[29 67]
[29 67]


In [86]:
print(x.dot(y))
print(np.dot(x, y))


[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [90]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # 모든 요소를 합한 값을 연산; 출력 "10"
print(np.sum(x, axis=0))  # 각 열에 대한 합을 연산; 출력 "[4 6]"
print(np.sum(x, axis=1))  # 각 행에 대한 합을 연산; 출력 "[3 7]"


10
[4 6]
[3 7]


In [94]:
x = np.array([[1,2], [3,4]])
print (x)

[[1 2]
 [3 4]]


In [95]:
print (x.T) 

[[1 3]
 [2 4]]


In [96]:
v = np.array([1,2,3])
print (v)    # 출력 "[1 2 3]"

[1 2 3]


In [97]:
print (v.T)  # 출력 "[1 2 3]"


[1 2 3]


In [99]:
import numpy as np

xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [100]:
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
print(result)

[1.1, 2.2, 1.3, 1.4, 2.5]


In [101]:
result2 = np.where(cond, xarr, yarr)
print(result2)

[1.1 2.2 1.3 1.4 2.5]


In [103]:
arr = np.random.randn(4,4)
print(arr)

[[-0.72922472  0.77401913  1.85117552  0.4476437 ]
 [ 0.72437257  0.16981834 -0.03395562 -1.36087772]
 [ 1.29281129 -1.24008488 -0.02961405 -0.56256753]
 [ 0.31596887  0.41335643  0.93914386  0.95997819]]


In [106]:
print(np.where(arr>0, 1, -1))

[[-1  1  1  1]
 [ 1  1 -1 -1]
 [ 1 -1 -1 -1]
 [ 1  1  1  1]]


In [107]:
print(np.where(arr>0, 0, arr))


[[-0.72922472  0.          0.          0.        ]
 [ 0.          0.         -0.03395562 -1.36087772]
 [ 0.         -1.24008488 -0.02961405 -0.56256753]
 [ 0.          0.          0.          0.        ]]


In [111]:
samples = np.random.normal(size=(4,4))
print(samples)

[[-0.34385365  0.63142926 -1.13943647  0.62654491]
 [ 0.0811377   0.32321107  0.16168429  0.36678637]
 [-0.82808874  1.25015551 -1.70138352  0.96574278]
 [ 0.10399125  0.0773626   0.11732263  0.78934815]]


In [112]:
from random import normalvariate 
N = 1000000

In [113]:
%timeit samples = [normalvariate(0,1) for _ in range(N)]

621 ms ± 4.66 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [114]:
%timeit np.random.normal(size=N)

23.6 ms ± 296 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
